# Generated by Django 5.2.4 on 2025-07-24 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_organizacao_vinculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoMonitorados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=25, verbose_name='Número do Processo')),
                ('orgao_julgador', models.CharField(max_length=255, verbose_name='Órgão Julgador')),
                ('ultima_movimentacao', models.CharField(max_length=255, verbose_name='Última Movimentação Processual')),
                ('data_ultima_movimentacao', models.DateField(verbose_name='Data Última Movimentação')),
                ('cpf_relacionado', models.CharField(max_length=14, verbose_name='CPF Relacionado')),
                ('organizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='website.organizacao')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='processos_monitorados',
            field=models.ManyToManyField(blank=True, related_name='monitorados_por_usuarios', to='website.processomonitorados'),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='processos_monitorados',
            field=models.ManyToManyField(blank=True, related_name='monitorados_por_organizacao', to='website.processomonitorados'),
        ),
    ]
