# Generated by Django 5.2.4 on 2025-07-24 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_processomonitorados_customuser_processos_monitorados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processomonitorados',
            name='cpf_relacionado',
        ),
        migrations.RemoveField(
            model_name='processomonitorados',
            name='organizacao',
        ),
    ]
