# Generated by Django 5.2.4 on 2025-07-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_processomonitorados_cpf_relacionado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processomonitorados',
            name='data_ultima_movimentacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Última Movimentação'),
        ),
        migrations.AlterField(
            model_name='processomonitorados',
            name='orgao_julgador',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Órgão Julgador'),
        ),
        migrations.AlterField(
            model_name='processomonitorados',
            name='ultima_movimentacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Última Movimentação Processual'),
        ),
    ]
