@startsalt Lista de Processos do Usuário
skinparam dpi 200

{
    {* <b>CNJ PushNotification | . . . | Meus Processos (42) | Notificações (5) | Meu Perfil | Minhas Organizações | Sair }
    .
    {/ <b>Meus Processos (42) | Organização A | Organização B | Organização C}
    {
    Processos vinculados ao meu CPF diretamente
    [Acrescentar Processo]
    .
        {T#
        +<b>Número do Processo | <b>Órgão Julgador | <b>Última Movimentação Processual | <b>Data Última Movimentação Processual
        +0000000-00.0000.0.00.0000 | Tribunal de Justiça | Movimentação Processual 1 | 01/01/2023
        +0000000-00.0000.0.00.0000 | Tribunal Regional Federal | Movimentação Processual 2 | 02/01/2023
        +0000000-00.0000.0.00.0000 | Tribunal Superior | Movimentação Processual 3 | 03/01/2023
        +0000000-00.0000.0.00.0000 | Tribunal de Justiça | Movimentação Processual 4 | 04/01/2023
        +0000000-00.0000.0.00.0000 | Tribunal Regional do Trabalho | Movimentação Processual 5 | 05/01/2023
        +0000000-00.0000.0.00.0000 | Tribunal de Justiça Militar | Movimentação Processual 6 | 06/01/2023
        }
    .
    }
    .
}
@endsalt
