@startsalt Lista de Notificações
skinparam dpi 200

{
    {* <b>CNJ PushNotification | . . . | Meus Processos (42) | Notificações (5) | Meu Perfil | Minhas Organizações | Sair }

    .
    <b> Notificações (127) 
    [Marcar Todas como Lidas]
    .

    {/ <b>Meus Processos (42) | Organização A | Organização B | Organização C}
    {
    Notificações dos Processos vinculados ao meu CPF diretamente
    .
        {#
        <b>Data | <b>Número do Processo | <b>Órgão Julgador | <b>Movimentação Processual | <b>Ações
        01/01/2023 | 0000000-00.0000.0.00.0000 | Tribunal de Justiça | Movimentação Processual 1 | {[Visualizar]|[Marcar como lida]|[Excluir]}
        02/01/2023 | 0000000-00.0000.0.00.0000 | Tribunal Regional Federal | Movimentação Processual 2 | {[Visualizar]|[Marcar como lida]|[Excluir]}
        03/01/2023 | 0000000-00.0000.0.00.0000 | Tribunal Superior | Movimentação Processual 3 | {[Visualizar]|[Marcar como lida]|[Excluir]}
        04/01/2023 | 0000000-00.0000.0.00.0000 | Tribunal de Justiça | Movimentação Processual 4 | {[Visualizar]|[Marcar como lida]|[Excluir]}
        05/01/2023 | 0000000-00.0000.0.00.0000 | Tribunal Regional do Trabalho | Movimentação Processual 5 | {[Visualizar]|[Marcar como lida]|[Excluir]}
        06/01/2023 | 0000000-00.0000.0.00.0000 | Tribunal de Justiça Militar | Movimentação Processual 6 | {[Visualizar]|[Marcar como lida]|[Excluir]}
        07/01/2023 | 0000000-00.0000.0.00.0000 | Tribunal de Justiça | Movimentação Processual 7 | {[Visualizar]|[Marcar como lida]|[Excluir]}
        08/01/2023 | 0000000-00.0000.0.00.0000 | Tribunal Regional Federal | Movimentação Processual 8 | {[Visualizar]|[Marcar como lida]|[Excluir]}
        09/01/2023 | 0000000-00.0000.0.00.0000 | Tribunal Superior | Movimentação Processual 9 | {[Visualizar]|[Marcar como lida]|[Excluir]}
        10/01/2023 | 0000000-00.0000.0.00.0000 | Tribunal de Justiça | Movimentação Processual 10 | {[Visualizar]|[Marcar como lida]|[Excluir]}
        11/01/2023 | 0000000-00.0000.0.00.0000 | Tribunal Regional do Trabalho | Movimentação Processual 11 | {[Visualizar]|[Marcar como lida]|[Excluir]}
        12/01/2023 | 0000000-00.0000.0.00.0000 | Tribunal de Justiça Militar | Movimentação Processual 12 | {[Visualizar]|[Marcar como lida]|[Excluir]}
        13/01/2023 | 0000000-00.0000.0.00.0000 | Tribunal de Justiça | Movimentação Processual 13 | {[Visualizar]|[Marcar como lida]|[Excluir]}
        14/01/2023 | 0000000-00.0000.0.00.0000 | Tribunal Regional Federal | Movimentação Processual 14 | {[Visualizar]|[Marcar como lida]|[Excluir]}
        
        }
    .
    }
}
@endsalt
